# Financials Version 1 API
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: Financials System API. 
  description: API for financials is defined here. Copyright © 2017 eGovernments Foundation, All Rights Reserved.
  
  contact:
    name: Manikanta P T, eGovernments Foundation. 
schemes:
  - https
basePath: '/restapi'
paths:
    /egf/voucher/create:
      post:
        summary: Create a new Voucher
        description: This API will create a Create voucher in the system after checking the header details and account code details.
        parameters:
          - name: Referer
            type: string
            in: header
            description: IP address of the referring system
            required: true
          - name: ulbCode
            in: query
            type: string
            description: Code of the ULB to create Voucher
            required: true
          - name: createVoucherHelper 
            in: body
            description: Financials Voucher details
            schema:
              $ref: '#/definitions/CreateVoucherHelper'
        responses:
          201:
            description: Voucher Created Successfully 
            schema:
              $ref: '#/definitions/VoucherResponse'
          400:
            description: Invalid Input
            schema:
              type: array
              items:
                $ref: '#/definitions/ErrorDetails'
                                
definitions:
    CreateVoucherHelper:
      title: The header object for creating Voucher.
      type: object
      properties:
        headerDetails:
          properties:
            vouchername:
              type: string
              description: Voucher Name for the Header Detils
            vouchertype:
              type: string
              description: Voucher Type for the Header Detils
              enum:
              - JOURNALVOUCHER
              - CONTRA
              - RECEIPT
              - PAYMENT
            description:
              type: string
              description: Voucher Description for the Header Detils
            voucherdate:
              type: string
              format: date
              description: Voucher date to create voucher in format of  (DD-MM-YYYY)
            fundcode:
              type: string
              description: Fund code of the fund
            departmentcode:
              type: string
              description: Department code of the department
            functioncode:
              type: string
              description: Function code of the function
            moduleid:
              type: string
              description: Module id to create voucher
            schemecode:
              type: string
              description: Scheme code to create voucher
            subschemecode:
              type: string
              description: Sub-Scheme code to create voucher
            functionarycode:
              type: string
              description: Functionary code to create voucher
            fundsourcecode:
              type: string
              description: Fund Source code to create voucher
          required:
            - vouchername
            - vouchertype
            - voucherdate
            - fundcode
            - departmentcode
            - functioncode
            - moduleid
              
        accountCodeDetails:
          type:  array
          description:  Account Code Details for the voucher
          uniqueItems: true
          items:
            $ref: "#/definitions/AccountCodeDetail"
        subledgerDetails:
          type:  array
          description:  Subledger Details for the voucher
          uniqueItems: true
          items:
            $ref: "#/definitions/SubledgerDetail"
      required:
        - headerDetails
        - accountCodeDetails
        
    VoucherResponse:
      type: object
      description: Voucher Response
      properties:
        voucherNumber:
          type: string
          description: Autogenerated voucher number of the saved voucher
          
    ErrorDetails:
      type: object
      description: Details of the error
      properties:
        errorCode:
          type: string
          description: error code
        errorMessage:
          type: string
          description: Detailed error message
          
    AccountCodeDetail:
      type: object
      description: List of Account Code Detail (Both Debit and Credit amounts can not be greater than zero for any given Glcode) 
      properties:
        glcode:
          type: string
          description: Glcode of the Account Code Details
        debitamount:
          type: number
          format: double
          description: Debit amount of the Account Code Details
          maxLength: 999999999
        creditamount:
          type: number
          format: double
          description: Credit amount of the Account Code Details
          maxLength: 999999999
        narration:
          type: string
          description: Narration of the Account Code Details
      required:
        - glcode
        - debitamount
        - creditamount
        
    SubledgerDetail:
      type: object
      description: Bill Payee details will have the subledger details of each glcode that is used in billdetails. (Both Debit and Credit amounts can not be greater than zero for any given Glcode)
      properties:
        glcode:
          type: string
          description: Glcode of the Bill Payee Details
        detailtypeid:
          type: string
          description: Subledger type of the account code. This API will support only- contractor and PROJECTCODE.
        detailkeyid:
          type: string
          description: Contractor code (if account detail type is contractor) and WIN code (if account detail type is PROJECTCODE)
        debitamount:
          type: number
          format: double
          description: Debit amount of the subledger details
          maxLength: 999999999
        creditamount:
          type: number
          format: double
          description: Credit amount of the subledger details
          maxLength: 999999999
      required:
        - glcode
        - detailtypeid
        - detailkeyid
        - debitamount
        - creditamount